- name: install python-software-properties
  apt: 
    name: python3-software-properties
    state: present
- name: Add webupd8team/java  repository from PPA
  ansible.builtin.apt_repository:
    repo: 'ppa:webupd8team/java'
    codename: trusty
- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
- name: install default-jdk
  apt:
    name: default-jdk
    state: present
- name: Create directory 
  file: 
    path: /home/edureka/Downloads
    state: directory
- name: Download maven
  get_url:
    url: http://apache.mirror.digitalpacific.com.au/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
    dest: /home/edureka/Downloads/apache-maven-3.3.9-bin.tar.gz
- name: Extract archive
  unarchive: 
    src: /home/edureka/Downloads/apache-maven-3.3.9-bin.tar.gz
    dest: /opt
    remote_src: yes
