- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
- name: install default-jdk
  apt: 
    name: default-jdk
    state: present
- name: add group "tomcat"
  group:  
    name: tomcat
- name: add user "tomcat"
  user:
    name: tomcat
    group: tomcat
    createhome: no
- name: Download Tomcat
  get_url:  
    url: https://downloads.apache.org/tomcat/tomcat-8/v8.5.69/bin/apache-tomcat-8.5.69.tar.gz
    dest: /tmp/apache-tomcat-8.5.69.tar.gz
- name: Extract archive
  unarchive: 
    src: /tmp/apache-tomcat-8.5.69.tar.gz
    dest: /opt
    remote_src: yes
- name: create symlink
  file:  
    src: /opt/apache-tomcat-8.5.69
    path: /opt/tomcat
    state: link
- name: Change ownership of Tomcat installation
  file:
    path: /opt/tomcat
    owner: tomcat
    group: tomcat
    mode: 0755
    state: directory
    recurse: yes
- name: create tomcat.service file
  file: 
    path: /etc/systemd/system/tomcat.service
    state: touch
- name: create tomcat service
  blockinfile:
    path: /etc/systemd/system/tomcat.service
    block: |
      [Unit]
      Description=Apache Tomcat Web Application Container
      After=network.targetd

      [Service]
      Type=forking
      Environment=JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre
      Environment=CATALINA_PID=/opt/tomcat/temp/tomcat.pid
      Environment=CATALINA_HOME=/opt/tomcat
      Environment=CATALINA_BASE=/opt/tomcat
      Environment='CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC'
      Environment='JAVA_OPTS=-Djava.awt.headless=true -Djava.security.egd=file:/dev/./urandom'

      ExecStart=/opt/tomcat/bin/startup.sh
      ExecStop=/opt/tomcat/bin/shutdown.sh

      User=tomcat
      Group=tomcat
      UMask=0007
      RestartSec=10
      Restart=always
      
      [Install]
      WantedBy=multi-user.target
- name: enable & start tomcat service
  systemd:
    name: tomcat
    state: started
    enabled: yes
